version: "3"

services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    links:
      - mysql
    volumes:
      - ./app:/go/src/github.com/mashita1023/test-api
    environment:
      GO111MODULE: "on"
#      http_proxy: "http://proxy.nagaokaut.ac.jp:8080"
#      https_proxy: "http://proxy.nagaokaut.ac.jp:8080"

  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pwd
 #     http_proxy: "http://proxy.nagaokaut.ac.jp:8080"
 #     https_proxy: "http://proxy.nagaokaut.ac.jp:8080"

  adminer:
    container_name: adminer
    image: adminer
    links:
      - mysql
    ports:
      - 8080:8080
