version: "3"

services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    restart: always
    links:
      - mysql
    volumes:
      - ./app:/go/src/github.com/NUTFes/seeft

  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    environment:
      MYSQL_DATABASE: seeft
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pwd
