version: "3"

services:
  server:
    container_name: api
    build:
      context: .
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    links:
      - db
    volumes:
      - ./app:/app
#    env_file:
#      - proxy.env
#    environment:
#      http_proxy: "http://proxy.nagaokaut.ac.jp:8080"
#      https_proxy: "http://proxy.nagaokaut.ac.jp:8080"

  db:
    container_name: db
    image: mariadb:10.7.1
    hostname: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    environment:
      MYSQL_DATABASE: seeft
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pwd

  adminer:
    container_name: adminer
    image: adminer
    links:
      - db
    ports:
      - 8080:8080
