name: seeft_api
description: seeft's backend API server.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  path: ^1.8.0
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  mysql1: ^0.19.2
  hotreloader: ^3.0.3
  logging: ^1.0.2
  
dev_dependencies:
  lints: ^2.0.0
  args: ^2.3.0
  intl: ^0.17.0
  test: ^1.21.1
  analyzer: ^4.0.0

analyzer:
  exclue:
    - sql/sql.dart
  errors:
    # ignore
    unnecessary_new: ignore
