CREATE TABLE IF NOT EXISTS shifts(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  date varchar(255) NOT NULL,
  time VARCHAR(255) NOT NULL,
  work VARCHAR(255) NOT NULL,
  weather VARCHAR(255) NOT NULL,
  log TINYINT(1) NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
