CREATE TABLE IF NOT EXISTS permissions (
  `user_id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `allow_shift` BOOLEAN NOT NULL DEFAULT FALSE,
  `allow_task` BOOLEAN NOT NULL DEFAULT FALSE,
  `allow_user` BOOLEAN NOT NULL DEFAULT FALSE,
  `allow_property` BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
