CREATE TABLE IF NOT EXISTS tasks (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `task` VARCHAR(50) NOT NULL,
  `color` VARCHAR(6) NOT NULL DEFAULT "fffafa",
  `place` VARCHAR(50) NOT NULL,
  `url` VARCHAR(220) NOT NULL,
  `superviser` VARCHAR(50) NOT NULL,
  `notes` TINYTEXT,
  `year_id` INT UNSIGNED NOT NULL,
  `created_user_id` INT UNSIGNED NOT NULL,
  `updated_user_id` INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
