CREATE TABLE IF NOT EXISTS years (
  id INT UNSIGNED UNIQUE NOT NULL,
  `year` INT UNSIGNED UNIQUE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
