CREATE TABLE IF NOT EXISTS bureaus (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `bureau`  VARCHAR(20) NOT NULL,
  `color` BINARY(6) NOT NULL DEFAULT hex(0xfffafa),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
