name: Analyzer

on:
  pull_request:
    type: [opened, synchronize]
  push:
    branched: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dart:stable
      
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: dart pub get
      - name: analyzer
        run: dart analyze --fatal-warnings .
