name: Analyzer

on:
  pull_request:
    type: [opened, synchronize]
  push:
    branched: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
      
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: pub get
      - name: analyzer
        run: dartanalyzer --fatal-warnings --fatal-infos .
